"use client";
import { useState } from "react";

const cases={
 contract:{label:"Contract",code:`cell inc(x: u32[0..99]) -> u32:\n    requires x < 100\n    ensures result == x + 1\n\n    val next = x + 1\n    assert next <= 100\n    next`,notes:["requires establishes a precondition","ensures describes the result contract","assert becomes a proof obligation","u32 range refinement carries bound information"]},
 loop:{label:"Loop",code:`cell sum_to(n: u32) ->:\n    requires n <= 10\n\n    val mut i: u32 = 0\n    val mut acc: u32 = 0\n\n    while i < n invariant i <= n decreases n - i:\n        acc = acc + i\n        i = i + 1\n\n    assert i == n\n    yield acc`,notes:["invariant is visible to the verifier","decreases is a termination-oriented hint","mutable state remains explicit","this example mirrors a repository verification fixture"]},
 trust:{label:"FFI trust",code:`extern cell native_read(fd: u32) -> u32\ntrusted extern cell audited_clock() -> u32\n\ncell read(fd: u32) -> u32:\n    unsafe:\n        native_read(fd)`,notes:["untrusted extern calls require an unsafe boundary","trusted extern is an explicit trust declaration","trusted does not mean automatically proved","FFI remains part of the trusted computing base"]},
} as const;
type Key=keyof typeof cases;
export default function PlaygroundPage(){const [active,setActive]=useState<Key>("contract");const item=cases[active];return <>
<section className="subpage-hero"><div className="page-shell subpage-hero-grid"><div><div className="eyebrow">Language explorer</div><h1>Read Aura syntax with its proof semantics beside it.</h1><p>This is an interactive documentation explorer, not a browser-hosted Aura compiler or Z3 session. It intentionally demonstrates syntax and reasoning vocabulary without fabricating verification results.</p></div><aside className="subpage-summary"><dl><div><dt>Mode</dt><dd>documentation explorer</dd></div><div><dt>Compiler execution</dt><dd>no</dd></div><div><dt>Examples</dt><dd>reference/repo aligned</dd></div><div><dt>Goal</dt><dd>learn semantics</dd></div></dl></aside></div></section>
<section className="page-section compact"><div className="page-shell explorer-shell"><div className="explorer-head"><strong>Aura source explorer</strong><span>not a live compiler</span></div><div className="explorer-tabs">{(Object.keys(cases) as Key[]).map(k=><button type="button" onClick={()=>setActive(k)} className={k===active?"is-active":""} key={k}>{cases[k].label}</button>)}</div><div className="explorer-body"><div className="explorer-code"><pre><code>{item.code}</code></pre></div><div className="explorer-notes"><div className="eyebrow">What to notice</div><div className="explorer-points">{item.notes.map(n=><div key={n}>{n}</div>)}</div></div></div></div></section>
</>}
