import Link from "next/link";
import { Icon } from "@/components/Icon";
import { SectionHeading } from "@/components/SectionHeading";
import { StatusBadge } from "@/components/StatusBadge";

export const metadata = { title: "Ecosystem", description: "Aura Sentinel, package tooling, Nexus, Lumina, SDK, FFI, Android and release-engineering surfaces." };

const packageCommands = ["init", "add", "remove", "list", "publish", "verify"];
export default function EcosystemPage(){return <>
<section className="subpage-hero"><div className="page-shell subpage-hero-grid"><div><div className="eyebrow">Ecosystem</div><h1>The product surface around the compiler already exists.</h1><p>Aura includes package management, an SDK, standard library, language server, Sentinel, FFI, Nexus plugins, Lumina, domain integrations and Android/release tooling. Each is presented with its real implementation status, not as a frozen platform guarantee.</p></div><aside className="subpage-summary"><dl><div><dt>IDE</dt><dd>Sentinel · Tauri 2</dd></div><div><dt>Packages</dt><dd>aura-pkg</dd></div><div><dt>Plugin host</dt><dd>Nexus</dd></div><div><dt>Application layer</dt><dd>Lumina · evolving</dd></div></dl></aside></div></section>
<section className="page-section" id="sentinel"><div className="page-shell sentinel-grid"><div className="sentinel-copy"><div className="eyebrow">Sentinel</div><h3>An editor built around proof feedback, not just syntax highlighting.</h3><p>`editors/sentinel-app` is a Tauri 2 + CodeMirror application. Aura’s language server owns proof streaming, structured diagnostics, counterexample transport, caches and debugger/performance integration so Sentinel can render language-specific workflows.</p><div className="feature-list"><div><span className="feature-icon"><Icon name="proof" size={14}/></span><div><strong>Proof phases</strong><span>Non-blocking custom LSP stream states.</span></div></div><div><span className="feature-icon"><Icon name="code" size={14}/></span><div><strong>Counterexample UX</strong><span>Structured payloads instead of parsing raw solver text.</span></div></div><div><span className="feature-icon"><Icon name="terminal" size={14}/></span><div><strong>Debug path</strong><span>AVM/native-oriented debugging infrastructure lives in the platform.</span></div></div></div></div><div className="content-card"><div className="eyebrow">Protocol surface</div><h3>Aura protocol v1</h3><pre className="command-block"><code>{`aura/proofsStreamStart\naura/proofsStreamCancel\n\nstart → phase(parse)\n      → phase(sema)\n      → phase(normalize)\n      → phase(z3)\n      → done | error | cancelled`}</code></pre><p>Aura-specific protocol compatibility is versioned independently from standard LSP behavior.</p></div></div></section>
<section className="page-section" id="packages"><div className="page-shell"><SectionHeading eyebrow="Packages" title="A package system with integrity and signing primitives." body="`aura-pkg` contains cache, registry, resolver, lockfile, security, signing, metadata and command modules. Documentation historically describes more commands than the executable surface; this site lists only code-backed operations."/><div className="two-col"><article className="content-card"><h3>Standalone `aura-pkg`</h3><div className="feature-list">{packageCommands.map(c=><div key={c}><span className="feature-icon"><Icon name="package" size={13}/></span><div><strong>{c}</strong><span>Current standalone command surface.</span></div></div>)}</div></article><article className="content-card"><h3>Supply-chain building blocks</h3><ul><li>SHA-256 integrity</li><li>SemVer-oriented resolution</li><li>artifact download/cache</li><li>lockfile state</li><li>optional Ed25519 signing</li></ul><p>Public registry uptime/SLA is not claimed without operational evidence.</p></article></div></div></section>
<section className="page-section" id="nexus"><div className="page-shell"><SectionHeading eyebrow="Nexus" title="Domain features do not all have to become core syntax."/><div className="three-col"><article className="content-card"><div className="tool-card-head"><h3>aura-nexus</h3><StatusBadge tone="proof">workspace</StatusBadge></div><p>Plugin manifest/integration layer that can participate in build and verification paths.</p></article><article className="content-card"><div className="tool-card-head"><h3>aura-plugin-ai</h3><StatusBadge tone="evolving">optional</StatusBadge></div><p>AI-domain integration surface backed by a real workspace component; capability claims remain example/module-specific.</p></article><article className="content-card"><div className="tool-card-head"><h3>aura-plugin-iot</h3><StatusBadge tone="evolving">optional</StatusBadge></div><p>IoT-oriented extension path with verifier-related feature integration.</p></article></div></div></section>
<section className="page-section" id="lumina"><div className="page-shell"><SectionHeading eyebrow="Lumina" title="An application layer growing beside the core language." body="Lumina is a substantial plugin, not a mockup: the repo contains Raylib support, layout/render syntax, input handling, TextInput, Box, grid work, image fit and audio controls plus real examples. It remains an evolving application/UI layer rather than a frozen cross-platform GUI contract."/><div className="two-col"><article className="content-card"><h3>Current vertical slice</h3><pre className="command-block"><code>{`import aura::lumina\n\ncell main():\n    layout:\n        Grid(columns: 2, gap: 16) {\n            render: Box(...)\n            render: Button(label: \"Play\") {\n                on_click: ~> { ... }\n            }\n        }`}</code></pre></article><article className="content-card"><h3>Repository-backed work</h3><ul><li>Raylib-backed rendering feature</li><li>layout primitives and styling</li><li>interactive input + TextInput</li><li>Box and grid layout</li><li>image fit modes</li><li>audio controls and examples</li></ul><Link href="/gallery" className="button-text">See repository examples <Icon name="arrow" size={14}/></Link></article></div></div></section>
<section className="page-section" id="android"><div className="page-shell"><SectionHeading eyebrow="Android" title="A real integration path, not a universal platform promise."/><div className="three-col"><article className="content-card"><h3>SDK / NDK</h3><p>Setup automation prepares Android toolchains used by the repository workflow.</p></article><article className="content-card"><h3>Runtime cross-build</h3><p>`aura-rt` is exercised for aarch64-linux-android and armv7-linux-androideabi paths in CI.</p></article><article className="content-card"><h3>APK workflow</h3><p>Sample APK automation plus emulator/build helper tooling demonstrate a vertical integration slice.</p></article></div></div></section>
</>}
