name: Feature request
description: Propose a change or addition
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem you're trying to solve and what success looks like.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - language/compiler
        - verifier (Z3 Gate)
        - aura CLI
        - aura-lsp
        - Sentinel IDE
        - Android/mobile
        - docs
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What pain point are you experiencing?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: scope
    attributes:
      label: Scope / notes
      description: Any constraints, migration concerns, or prior art.
