import { SectionHeading } from "@/components/SectionHeading";
import { StatusBadge } from "@/components/StatusBadge";

export const metadata = { title: "Releases", description: "Aura version reconciliation, pre-stable release state and nightly/beta/stable promotion policy." };

export default function ReleasesPage(){return <>
<section className="subpage-hero"><div className="page-shell subpage-hero-grid"><div><div className="eyebrow">Releases</div><h1>Release state without version theater.</h1><p>Aura’s repository currently carries a `0.2.0` workspace version, a `2026` edition concept, component-specific versions and historical milestone documents that use later labels. This page separates those namespaces and describes the intended release channels without pretending a stable GA artifact already exists.</p></div><aside className="subpage-summary"><dl><div><dt>Workspace</dt><dd>0.2.0</dd></div><div><dt>Edition</dt><dd>2026</dd></div><div><dt>Public state</dt><dd>pre-stable</dd></div><div><dt>Policy</dt><dd>nightly → beta → stable</dd></div></dl></aside></div></section>
<section className="page-section"><div className="page-shell"><SectionHeading eyebrow="Channels" title="Stability should be promoted, not declared."/><div className="three-col"><article className="content-card"><div className="tool-card-head"><h3>Nightly</h3><StatusBadge tone="evolving">iteration</StatusBadge></div><p>Automated builds from main may move quickly and can contain unstable behavior.</p></article><article className="content-card"><div className="tool-card-head"><h3>Beta</h3><StatusBadge tone="info">candidate</StatusBadge></div><p>Release candidates for the next stable line with more constrained breaking changes and stronger smoke validation.</p></article><article className="content-card"><div className="tool-card-head"><h3>Stable</h3><StatusBadge tone="proof">policy target</StatusBadge></div><p>Tagged releases with explicit compatibility expectations once CI, installers, release notes and regression gates justify promotion.</p></article></div></div></section>
<section className="page-section"><div className="page-shell"><SectionHeading eyebrow="Current release truth" title="The site does not call Aura v1.0 stable."/><div className="status-matrix"><div className="status-matrix-row is-head"><strong>Namespace</strong><strong>Observed</strong><strong>Interpretation</strong></div><div className="status-matrix-row"><strong>Workspace</strong><code>0.2.0</code><span>Primary Rust package version.</span></div><div className="status-matrix-row"><strong>Language edition</strong><code>2026</code><span>Syntax/feature compatibility namespace.</span></div><div className="status-matrix-row"><strong>aura-pkg</strong><code>1.0.0</code><span>Component version, not whole-language GA.</span></div><div className="status-matrix-row"><strong>Historical milestones</strong><code>v0.3 / v1.0</code><span>Planning/subsystem milestone language, not a unified stable release.</span></div></div></div></section>
<section className="page-section"><div className="page-shell"><div className="two-col"><article className="content-card"><div className="eyebrow">Promotion evidence</div><h3>What a stable promotion should prove.</h3><ul><li>workspace + compatibility CI genuinely green</li><li>trusted-core baseline intentional and reviewed</li><li>artifact/installer smoke tests pass</li><li>release notes and version contract written</li><li>no known backend/proof regressions in the stable scope</li></ul></article><article className="content-card"><div className="eyebrow">Artifacts</div><h3>SDK, Sentinel and VSIX are release outputs, not assumptions.</h3><p>Repository release tooling knows how to stage portable SDK and Sentinel-related artifacts. The public website should expose binary download CTAs only after those files are actually published and integrity metadata is available.</p></article></div></div></section>
</>}
