import { SectionHeading } from "@/components/SectionHeading";
import { StatusBadge } from "@/components/StatusBadge";
import { TOOLCHAIN_SURFACES, WORKSPACE_MEMBERS } from "@/lib/siteData";

export const metadata = { title: "Toolchain", description: "Aura compiler architecture, CLI, AVM, C-oriented backend, evolving LLVM IR path, FFI and workspace crates." };

export default function ToolchainPage(){return <>
<section className="subpage-hero"><div className="page-shell subpage-hero-grid"><div><div className="eyebrow">Toolchain</div><h1>One language. Several deliberately different execution paths.</h1><p>The primary CLI orchestrates parsing, semantic analysis, IR, verification, AVM execution, native-oriented backends, FFI and project tooling. The site keeps backend maturity and feature gates visible instead of collapsing them into one “native compiler” claim.</p></div><aside className="subpage-summary"><dl><div><dt>Primary CLI</dt><dd>aura</dd></div><div><dt>Dev execution</dt><dd>AVM</dd></div><div><dt>Default backend</dt><dd>C-oriented</dd></div><div><dt>LLVM</dt><dd>feature-gated · evolving</dd></div></dl></aside></div></section>
<section className="page-section compact"><div className="page-shell"><pre className="command-block"><code>{`aura build main.aura\naura run main.aura\naura verify main.aura --smt-profile ci\naura test .\naura lint main.aura\naura fmt main.aura --check\naura bindgen --header demo.h --out build/bindgen`}</code></pre></div></section>
<section className="page-section"><div className="page-shell"><SectionHeading eyebrow="Command surfaces" title="Code-backed tooling, labeled by maturity."/><div className="toolchain-grid">{TOOLCHAIN_SURFACES.map(tool=><article className="tool-card" key={tool.title}><div className="tool-card-head"><h3>{tool.title}</h3><StatusBadge tone={tool.status==="evolving"?"evolving":"proof"}>{tool.status}</StatusBadge></div><span className="tool-command">{tool.command}</span><p>{tool.body}</p></article>)}</div></div></section>
<section className="page-section"><div className="page-shell"><SectionHeading eyebrow="Execution model" title="AVM is not LLVM, and hybrid is not a JIT." body="The distinction matters. AVM provides a development execution path. The C backend supplies a portable native-oriented route. LLVM IR emission exists behind a feature gate and remains evolving. Current source explicitly says automatic AVM → LLVM promotion inside hybrid execution is not yet implemented."/><div className="three-col"><article className="content-card"><div className="tool-card-head"><h3>AVM</h3><StatusBadge tone="proof">code-backed</StatusBadge></div><p>Development VM / interpreter for the low-friction edit-run loop, with debug machinery in `aura-interpret`.</p></article><article className="content-card"><div className="tool-card-head"><h3>C backend</h3><StatusBadge tone="proof">code-backed</StatusBadge></div><p>C23-oriented emission is the default backend surface exposed by the CLI and a useful portability/differential anchor.</p></article><article className="content-card"><div className="tool-card-head"><h3>LLVM IR</h3><StatusBadge tone="evolving">evolving</StatusBadge></div><p>Implemented, feature-gated emission with codegen/debugger/pattern modules, but source still describes parts as phase/skeleton work.</p></article></div></div></section>
<section className="page-section"><div className="page-shell"><SectionHeading eyebrow="Workspace" title="The compiler is a monorepo architecture." body="Twenty-two workspace crates separate concerns so semantics, proof, execution and tooling can evolve without turning the primary CLI into a monolith."/><div className="status-matrix"><div className="status-matrix-row is-head"><strong>Crate</strong><strong>Role</strong><strong>Surface</strong></div>{WORKSPACE_MEMBERS.map(([name,role])=><div className="status-matrix-row" key={name}><code>{name}</code><span>{role}</span><span>workspace</span></div>)}</div></div></section>
<section className="page-section"><div className="page-shell"><div className="two-col"><article className="content-card"><div className="eyebrow">FFI</div><h3>Bridge native code without hiding the boundary.</h3><p>`aura-bridge` and `aura bindgen` create a path from C/C++ headers and link inputs into Aura. Refined type mapping is best-effort; generated bindings belong in the trusted/audited boundary.</p><pre className="command-block"><code>{`aura bindgen \\\n  --header demo.h \\\n  --out build/bindgen \\\n  --refine-types`}</code></pre></article><article className="content-card"><div className="eyebrow">Release engineering</div><h3>Artifacts can carry provenance.</h3><p>The release tooling implements deterministic archive metadata/order, SHA-256 hashing, attestation JSON, optional Windows signing and Sentinel sidecar staging.</p><pre className="command-block"><code>{`python tools/release/release.py --help`}</code></pre></article></div></div></section>
</>}
