import Link from "next/link";

import { DownloadArtifactCard } from "@/components/DownloadArtifactCard";
import { Icon } from "@/components/Icon";
import { SectionHeading } from "@/components/SectionHeading";
import { GITHUB_URL, STATUS } from "@/lib/siteData";

export const metadata = {
  title: "Downloads",
  description: "Download AuraSDK, Aura Sentinel editor integration and Sentinel desktop artifacts, or build the complete distribution from source.",
};

const sdkArtifacts = [
  {
    title: "AuraSDK",
    kind: "Portable SDK",
    description: "The complete portable developer bundle produced by Aura's release tool: the Aura CLI, aura-lsp, standard library, offline SDK documentation, styles and install scripts. Windows staging can also bundle the Z3 runtime DLL set.",
    detail: "Primary entry point for using Aura outside a source checkout.",
    href: "/downloads/aura-sdk.zip",
    filename: "aura-sdk.zip",
    primary: true,
  },
] as const;

const sentinelArtifacts = [
  {
    title: "Aura Sentinel for VS Code",
    kind: "VSIX",
    description: "VS Code integration for Aura's language server and proof-driven editor surfaces.",
    href: "/downloads/aura-sentinel.vsix",
    filename: "aura-sentinel.vsix",
  },
  {
    title: "Aura Sentinel App",
    kind: "Desktop executable",
    description: "Standalone Sentinel desktop shell with the Aura language-server sidecar staged into the application bundle.",
    href: "/downloads/aura-sentinel-app.exe",
    filename: "aura-sentinel-app.exe",
  },
  {
    title: "Aura Sentinel MSI",
    kind: "Windows installer",
    description: "MSI installer generated by the Sentinel Tauri release path when an MSI bundle is produced.",
    href: "/downloads/aura-sentinel.msi",
    filename: "aura-sentinel.msi",
  },
  {
    title: "Aura Sentinel Setup",
    kind: "Windows installer",
    description: "NSIS-style setup executable generated by the Sentinel Tauri release path when that bundle is produced.",
    href: "/downloads/aura-sentinel-setup.exe",
    filename: "aura-sentinel-setup.exe",
  },
] as const;

export default function DownloadsPage() {
  return (
    <>
      <section className="subpage-hero download-hero">
        <div className="page-shell subpage-hero-grid">
          <div>
            <div className="eyebrow">Aura distribution</div>
            <h1>Get the language. Get the proof tools. Get Sentinel.</h1>
            <p>
              Aura&apos;s repository contains a real release pipeline for a portable SDK, the language server,
              the Sentinel VS Code extension and standalone desktop artifacts. This page is the public
              distribution surface for those artifacts while keeping their actual deployment state visible.
            </p>
            <div className="hero-actions">
              <a className="button-primary" href="#sdk">Download AuraSDK <Icon name="arrow" size={15} /></a>
              <a className="button-secondary" href="#sentinel">Sentinel downloads</a>
              <a className="button-text" href={GITHUB_URL} target="_blank" rel="noreferrer">Build from source <Icon name="external" size={14} /></a>
            </div>
          </div>
          <aside className="subpage-summary">
            <dl>
              <div><dt>Workspace line</dt><dd>{STATUS.workspaceVersion}</dd></div>
              <div><dt>SDK alias</dt><dd>aura-sdk.zip</dd></div>
              <div><dt>Editor package</dt><dd>VSIX</dd></div>
              <div><dt>Desktop packages</dt><dd>EXE · MSI · Setup</dd></div>
            </dl>
          </aside>
        </div>
      </section>

      <section className="page-section compact download-intro-section">
        <div className="page-shell">
          <div className="download-trust-strip">
            <div><strong>Stable aliases</strong><span>The release tool copies latest artifact names into website/public/downloads.</span></div>
            <div><strong>Deterministic packaging</strong><span>SDK ZIP metadata and entry ordering are normalized by release.py.</span></div>
            <div><strong>Provenance-ready</strong><span>Optional SHA-256 attestation JSON can be emitted beside release artifacts.</span></div>
          </div>
        </div>
      </section>

      <section className="page-section" id="sdk">
        <div className="page-shell">
          <SectionHeading
            eyebrow="AuraSDK"
            title="One portable kit for the core Aura developer environment."
            body="The SDK release path stages the compiler CLI and language server together with the SDK standard library, documentation, styles and installer scripts. The website's stable latest alias is generated by the repository release tooling."
            aside={<Link href="/docs/getting-started" className="button-secondary">Getting started <Icon name="arrow" size={15} /></Link>}
          />
          <div className="download-grid single-feature">
            {sdkArtifacts.map((artifact) => <DownloadArtifactCard key={artifact.filename} {...artifact} />)}
          </div>
          <div className="download-build-note">
            <div>
              <span className="download-build-label">Build / stage the SDK and VSIX</span>
              <code>python tools/release/release.py --website --attest</code>
            </div>
            <p>This command builds the SDK, packages the Sentinel VSIX and places stable aliases under <code>website/public/downloads/</code>.</p>
          </div>
        </div>
      </section>

      <section className="page-section" id="sentinel">
        <div className="page-shell">
          <SectionHeading
            eyebrow="Aura Sentinel"
            title="Editor integration and a standalone proof-driven desktop environment."
            body="Sentinel is not one binary. Aura's release path has separate surfaces for the VS Code extension, the standalone desktop executable and Windows installer bundles."
            aside={<Link href="/ecosystem#sentinel" className="button-secondary">Sentinel architecture <Icon name="arrow" size={15} /></Link>}
          />
          <div className="download-grid">
            {sentinelArtifacts.map((artifact) => <DownloadArtifactCard key={artifact.filename} {...artifact} />)}
          </div>
          <div className="download-build-note">
            <div>
              <span className="download-build-label">Build / stage the complete Sentinel distribution</span>
              <code>python tools/release/release.py --sentinel-app --website --attest</code>
            </div>
            <p>On Windows, the Tauri build may additionally yield MSI and NSIS setup artifacts; when they exist, release.py copies their stable latest names into the website download directory.</p>
          </div>
        </div>
      </section>

      <section className="page-section dark-section">
        <div className="page-shell">
          <SectionHeading
            eyebrow="What is inside"
            title="The download center mirrors Aura's actual release architecture."
            body="The website does not invent package names. The stable aliases below are the names release.py itself writes into website/public/downloads when those artifacts are produced."
          />
          <div className="release-alias-grid">
            <div><code>aura-sdk.zip</code><span>Portable AuraSDK</span></div>
            <div><code>aura-sentinel.vsix</code><span>VS Code extension</span></div>
            <div><code>aura-sentinel-app.exe</code><span>Standalone Sentinel app</span></div>
            <div><code>aura-sentinel.msi</code><span>Windows MSI</span></div>
            <div><code>aura-sentinel-setup.exe</code><span>Windows setup executable</span></div>
          </div>
        </div>
      </section>

      <section className="page-section">
        <div className="page-shell">
          <div className="two-col">
            <article className="content-card">
              <div className="eyebrow">Source build</div>
              <h3>Build Aura directly from the repository</h3>
              <pre className="command-block"><code>{`git clone https://github.com/danielforface/aura-lang.git\ncd aura-lang\n\ncargo build -p aura --locked --no-default-features\ncargo run -p aura --locked --no-default-features -- --help`}</code></pre>
            </article>
            <article className="content-card">
              <div className="eyebrow">Verification</div>
              <h3>Enable the Z3-backed verifier path</h3>
              <pre className="command-block"><code>{`cargo run -p aura --features z3 -- \\\n  verify main.aura --smt-profile fast`}</code></pre>
            </article>
          </div>
        </div>
      </section>

      <section className="page-section compact">
        <div className="page-shell">
          <div className="closing-panel">
            <div>
              <h2>Aura is more than the compiler binary.</h2>
              <p>The public distribution surface keeps the SDK, proof tooling, language server and Sentinel together so the product can be installed as the platform it actually is.</p>
            </div>
            <Link href="/releases" className="button-secondary">Release model</Link>
          </div>
        </div>
      </section>
    </>
  );
}
